all: fibonacci prime permute bubblesort

fibonacci:
	gcc -Wall -ansi -pedantic fibonacci.c -o fibonacci
prime:
	gcc -fopenmp -Wall -ansi -pedantic prime.c -o prime
permute:
	gcc -Wall -ansi -pedantic permute.c -o permute
bubblesort:
	gcc -Wall -ansi -pedantic bubblesort.c -o bubblesort
clean:
	rm prime fibonacci permute bubblesort
